### PR TITLE
add luajit support

### PR DESCRIPTION
**Pull request by lazytiger**
add system_luajit feature to support luajit2.1

### CODE REVIEW

**Comment by jugglerchris** [comment]
Thanks, this looks great!
I'll take a closer look at the weekend, but I was wondering what the change in the allocation functions is for - is that just a difference in how LuaJIT is initialized?

**Comment by lazytiger** [comment]
Yes, Luajit has its own allocator, and lua_newstate is not allowed to be called directly, luaL_newstate is the only way now.

**Comment by jugglerchris** [comment]
Looks good to me, thanks!
Would you mind running `rustfmt`?  I think that's the only thing causing the CI builds to fail.

**Comment by lazytiger** [comment]
I have formatted the lua.rs but the bindgen issue arose, I can't figure out why.

**Comment by jugglerchris** [comment]
Thanks!  I've merged - the bindgen errors are not related.  For some reason the output from bindgen recently has become machine-dependent - I need to either fix it or make the checks laxer.
I will aim to get a new release out after fixing that and adding a luajit CI job.

**Comment by jugglerchris** [comment]
I've just published 0.19.6 with the LuaJIT support.  Thank you again!

**Comment by lazytiger** [comment]
You are too kind, I am glad to contribute to this repository, it's great.

**Pull request merged**
