### PR TITLE
Allow loading of binary lua files

### PR DESCRIPTION
**Pull request by allight**
This is useful for some testing applications.

### CODE REVIEW

**Comment by allight** [comment]
Failures seem to be the same ones that appear running `cargo test` on master.

**Comment by jugglerchris** [comment]
Hi,
Thanks for the contribution!
However it's deliberate that `load_chunk` doesn't load binary/compiled lua files, so this can't be merged as is.
The intention (which hasn't happened yet) is to add a new, `unsafe` API which does allow loading binary Lua files.  See #116 and #145 for some previous discussion.
I think a method on `Chunk` like:
```rust
pub unsafe fn into_function_unsafe(self) -> Result<Function<'lua>>
```
seems reasonable, but I'd be interested in whether you think that works for your use case.

I'll look into why the CI is failing.

**Comment by jugglerchris** [comment]
FWIW I've fixed the CI issues (which I raised separately as #207).

**Comment by jugglerchris** [comment]
This has been addressed as part of #236.

**Pull request closed without merging**
